sudo: required
services:
  - docker

language: node_js
node_js:
  - '6'

cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
  - "$HOME/.npm"

before_install:
  - npm install -g grunt-cli bower

script:
  # Set dev URLs
  # By default env variables contain production urls
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then
      export OPENSENSEMAP_API_URL=$OPENSENSEMAP_API_URL_DEV;
      export OPENSENSEMAP_MAPTILES_URL=$OPENSENSEMAP_MAPTILES_URL_DEV;
    fi
  - npm run build
  - docker build -t $IMAGE_NAME:$TRAVIS_BRANCH-temp .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

  - docker pull $IMAGE_NAME:$TRAVIS_BRANCH
  - docker tag $IMAGE_NAME:$TRAVIS_BRANCH $IMAGE_NAME:$TRAVIS_BRANCH-rollback
  - docker push $IMAGE_NAME:$TRAVIS_BRANCH-rollback

  - docker tag $IMAGE_NAME:$TRAVIS_BRANCH-temp $IMAGE_NAME:$TRAVIS_BRANCH
  - docker push $IMAGE_NAME:$TRAVIS_BRANCH

  - if [[ "$TRAVIS_TAG" != "" ]]; then
      docker tag $IMAGE_NAME:$TRAVIS_BRANCH-temp $IMAGE_NAME:$TRAVIS_TAG;
      docker push $IMAGE_NAME:$TRAVIS_TAG;
    fi
