[context.branch-deploy]
  publish = "dist/"
  command = "grunt build --target=build"
  environment = { OPENSENSEMAP_MAPTILES_URL = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", OPENSENSEMAP_API_URL = "https://api.testing.opensensemap.org" }

[[headers]]
  from = "/*"

  [headers.values]
    X-FRAME-OPTIONS = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age: 300"

[[headers]]
  from = "/scripts"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[headers]]
  from = "/styles"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[headers]]
  from = "/fonts"

  [headers.values]
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control = "public"

[[redirects]]
  from="/explore/*"
  to="/"
  status=200

[[redirects]]
  from="/account"
  to="/"
  status=200

[[redirects]]
  from="/interpolation"
  to="/"
  status=200

[[redirects]]
  from="/filter"
  to="/"
  status=200

[[redirects]]
  from="/download"
  to="/"
  status=200

[[redirects]]
  from="/register"
  to="/"
  status=200

[[redirects]]
  from="/about" 
  to="/" 
  status=200

[[redirects]]
  from="/imprint"
  to="/"
  status=200

[[redirects]]
  from="/privacy"
  to="/"
  status=200